name: 'Checkbox Action'
description: 'Checks or unchecks a checkbox in the body of the pull request.'
author: 'marocchino'
github-token:
  action-input:
    input: GITHUB_TOKEN
    is-default: true

  permissions:
    pull-requests: write
    pull-requests-reason: to update PR body

inputs:
  list:
    required: false
    description: 'Line separated List of checkboxes to modify. ex) list 1\nlist 2'
    default: ''
  matches:
    required: false
    description: 'Regular expression for the checkbox to modify.'
    default: ''
  action:
    required: false
    description: 'check, uncheck or detect. This default to check'
    default: 'check'
  error:
    required: false
    description: 'error, warn or ignore. Specifies whether to skip or raise an error when error occurred. This defaults to error'
    default: 'error'
  GITHUB_TOKEN:
    description: "The GitHub access token (e.g. secrets.GITHUB_TOKEN) used to update the body. This defaults to {{ github.token }}."
    default: "${{ github.token }}"
    required: false
outputs:
  checked:
    description: 'Returns a list of checked items from the previous modification as json in []string.'
  unchecked:
    description: 'Returns a list of unchecked items from the previous modification as json in []string.'
runs:
  using: 'node16'
  main: 'dist/index.js'
